package com.example.util

import com.example.data.TradeEntity
import java.util.concurrent.TimeUnit

object SampleTradeData {

    fun generateSampleTrades(): List<TradeEntity> {
        val now = System.currentTimeMillis()
        val oneDay = TimeUnit.DAYS.toMillis(1)

        return listOf(
            TradeEntity(
                id = 0,
                instrument = "NIFTY",
                strikeOrSymbol = "24800 CE",
                optionType = "CE",
                direction = "BUY",
                entryPrice = 142.0,
                slPrice = 118.0,
                target1 = 180.0,
                target2 = 210.0,
                target3 = 250.0,
                exitPrice = 195.0,
                quantity = 50,
                grossPnL = 2650.0,
                charges = 58.4,
                netPnL = 2591.6,
                points = 53.0,
                riskAmount = 1200.0,
                plannedRR = 1.58,
                actualRR = 2.21,
                status = "TARGET_HIT",
                setup = "CPR Breakout",
                indicators = listOf("CPR", "VWAP", "Volume Profile"),
                emotion = "Disciplined",
                mistake = "None (Followed Plan)",
                notes = "Clean morning breakout above Virgin CPR with massive institutional volume spike. Booked 80% at T1 extension and trailed remainder.",
                imageUris = emptyList(),
                entryTimestamp = now - (oneDay * 0) - TimeUnit.HOURS.toMillis(3),
                exitTimestamp = now - (oneDay * 0) - TimeUnit.HOURS.toMillis(1)
            ),
            TradeEntity(
                id = 0,
                instrument = "Bank Nifty",
                strikeOrSymbol = "51600 PE",
                optionType = "PE",
                direction = "BUY",
                entryPrice = 285.0,
                slPrice = 250.0,
                target1 = 340.0,
                target2 = 400.0,
                target3 = 450.0,
                exitPrice = 360.0,
                quantity = 30,
                grossPnL = 2250.0,
                charges = 62.1,
                netPnL = 2187.9,
                points = 75.0,
                riskAmount = 1050.0,
                plannedRR = 1.57,
                actualRR = 2.14,
                status = "TARGET_HIT",
                setup = "VWAP Bounce",
                indicators = listOf("VWAP", "EMA (9/21)", "RSI"),
                emotion = "Confident",
                mistake = "None (Followed Plan)",
                notes = "Price rejected 51800 resistance with bearish engulfing at VWAP. Good momentum, exited ahead of 51300 round support.",
                imageUris = emptyList(),
                entryTimestamp = now - (oneDay * 1) - TimeUnit.HOURS.toMillis(4),
                exitTimestamp = now - (oneDay * 1) - TimeUnit.HOURS.toMillis(2)
            ),
            TradeEntity(
                id = 0,
                instrument = "Sensex",
                strikeOrSymbol = "82000 CE",
                optionType = "CE",
                direction = "BUY",
                entryPrice = 310.0,
                slPrice = 275.0,
                target1 = 370.0,
                target2 = 420.0,
                target3 = 480.0,
                exitPrice = 275.0,
                quantity = 20,
                grossPnL = -700.0,
                charges = 52.0,
                netPnL = -752.0,
                points = -35.0,
                riskAmount = 700.0,
                plannedRR = 1.71,
                actualRR = -1.0,
                status = "SL_HIT",
                setup = "Opening Range Breakout (ORB)",
                indicators = listOf("Volume Profile", "EMA (9/21)"),
                emotion = "Anxious",
                mistake = "Chased Entry",
                notes = "Entered late at the high of day after first 15m candle. False breakout trapped buyers. SL respected strictly.",
                imageUris = emptyList(),
                entryTimestamp = now - (oneDay * 2) - TimeUnit.HOURS.toMillis(5),
                exitTimestamp = now - (oneDay * 2) - TimeUnit.HOURS.toMillis(4)
            ),
            TradeEntity(
                id = 0,
                instrument = "Crude Oil",
                strikeOrSymbol = "6100 PE",
                optionType = "PE",
                direction = "BUY",
                entryPrice = 115.0,
                slPrice = 95.0,
                target1 = 150.0,
                target2 = 180.0,
                target3 = 220.0,
                exitPrice = 168.0,
                quantity = 100,
                grossPnL = 5300.0,
                charges = 78.5,
                netPnL = 5221.5,
                points = 53.0,
                riskAmount = 2000.0,
                plannedRR = 1.75,
                actualRR = 2.65,
                status = "TARGET_HIT",
                setup = "Breakout & Retest",
                indicators = listOf("EMA (50/200)", "MACD", "Volume Profile"),
                emotion = "Patient",
                mistake = "None (Followed Plan)",
                notes = "Crude broke 6150 major support on MCX evening session. Retest confirmed with decreasing bull volume. Superb trend follow.",
                imageUris = emptyList(),
                entryTimestamp = now - (oneDay * 3) - TimeUnit.HOURS.toMillis(6),
                exitTimestamp = now - (oneDay * 3) - TimeUnit.HOURS.toMillis(1)
            ),
            TradeEntity(
                id = 0,
                instrument = "Natural Gas",
                strikeOrSymbol = "215 CE",
                optionType = "CE",
                direction = "BUY",
                entryPrice = 14.2,
                slPrice = 11.5,
                target1 = 18.0,
                target2 = 22.0,
                target3 = 26.0,
                exitPrice = 11.5,
                quantity = 1250,
                grossPnL = -3375.0,
                charges = 85.0,
                netPnL = -3460.0,
                points = -2.7,
                riskAmount = 3375.0,
                plannedRR = 1.41,
                actualRR = -1.0,
                status = "SL_HIT",
                setup = "Trendline Break",
                indicators = listOf("RSI", "MACD"),
                emotion = "FOMO",
                mistake = "Oversized / Over-leveraged",
                notes = "Position size was too large for EIA inventory volatility. Inventory report pushed price down immediately. Strict SL saved further drawdown.",
                imageUris = emptyList(),
                entryTimestamp = now - (oneDay * 5) - TimeUnit.HOURS.toMillis(7),
                exitTimestamp = now - (oneDay * 5) - TimeUnit.HOURS.toMillis(6)
            ),
            TradeEntity(
                id = 0,
                instrument = "NIFTY",
                strikeOrSymbol = "24600 PE",
                optionType = "PE",
                direction = "BUY",
                entryPrice = 108.0,
                slPrice = 90.0,
                target1 = 140.0,
                target2 = 170.0,
                target3 = 200.0,
                exitPrice = 152.0,
                quantity = 75,
                grossPnL = 3300.0,
                charges = 64.2,
                netPnL = 3235.8,
                points = 44.0,
                riskAmount = 1350.0,
                plannedRR = 1.77,
                actualRR = 2.44,
                status = "TARGET_HIT",
                setup = "EMA Pullback",
                indicators = listOf("EMA (9/21)", "VWAP", "RSI"),
                emotion = "Disciplined",
                mistake = "None (Followed Plan)",
                notes = "Pullback to 21 EMA on 5m timeframe. Bearish pin bar rejection. Flawless execution and disciplined trail.",
                imageUris = emptyList(),
                entryTimestamp = now - (oneDay * 7) - TimeUnit.HOURS.toMillis(3),
                exitTimestamp = now - (oneDay * 7) - TimeUnit.HOURS.toMillis(2)
            )
        )
    }
}
